export const sampleScenarios = [
  "서울 소재 스타트업이 포괄임금제를 폐지하고 선택근로제를 도입하려고 합니다. 연장근로, 야간수당, 최저임금 산정, 취업규칙 변경, 근로자 동의 절차를 확인하고 싶습니다.",
  "카페를 창업하려고 합니다. 영업신고, 식품위생 교육, 원산지 표시, 배달 판매, 미성년자 고용 기준을 한 번에 확인하고 싶습니다.",
  "오피스텔 임대차 계약을 갱신하려고 합니다. 보증금 증액, 계약갱신요구권, 전입신고, 확정일자, 중개수수료 관련 법령을 정리해 주세요.",
  "온라인 쇼핑몰이 개인정보 처리방침과 환불 규정을 바꾸려고 합니다. 전자상거래, 개인정보, 표시광고, 약관 관련 영향을 보고 싶습니다.",
  "공장을 증설하면서 대기배출시설과 폐기물 처리 절차를 검토해야 합니다. 인허가, 신고, 점검 체크리스트를 만들어 주세요.",
  "어린이 통학버스와 학원 운영 기준을 점검하려고 합니다. 도로교통법, 학원법, 안전교육 관련 법령을 확인해 주세요.",
];

export const lawData = [
  {
    id: "labor-standards-hours",
    title: "근로기준법",
    type: "법률",
    article: "제50조, 제52조, 제53조, 제56조, 제93조, 제94조",
    summary: "근로시간, 선택적 근로시간제, 연장근로, 가산임금, 취업규칙 작성·변경 기준",
    evidence: "선택적 근로시간제와 임금체계 변경은 근로시간 한도, 근로자대표 서면합의, 가산수당, 취업규칙 작성·변경 절차를 함께 점검해야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "hours", "wages", "amendment", "notice"],
    keywords: ["근로기준법", "근로시간", "연장근로", "야간수당", "휴일근로", "선택근로", "포괄임금", "취업규칙", "직원", "고용"],
    tasks: ["선택적 근로시간제 서면합의 요건 확인", "근로시간·휴게시간 재계산", "임금·수당 산정표 갱신", "취업규칙 변경 절차 확인"],
    relations: [{ target: "minimum-wage-act", type: "tension" }],
  },
  {
    id: "minimum-wage-act",
    title: "최저임금법",
    type: "법률",
    article: "제6조",
    summary: "최저임금 이상 지급 의무와 임금 산입 범위",
    evidence: "임금체계 변경 시 기본급, 고정수당, 상여금, 복리후생성 임금의 산입 여부를 분리해 확인해야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "wages"],
    keywords: ["최저임금", "급여", "임금", "수당", "통상임금", "상여금"],
    tasks: ["최저임금 산입 범위 비교", "급여명세서 항목 점검", "임금 부족분 발생 여부 산정"],
    relations: [{ target: "labor-standards-hours", type: "tension" }],
  },
  {
    id: "privacy-act",
    title: "개인정보 보호법",
    type: "법률",
    article: "제15조, 제22조, 제26조, 제30조",
    summary: "개인정보 수집·이용, 동의, 처리위탁, 처리방침 공개 기준",
    evidence: "개인정보 처리 목적, 보유기간, 제3자 제공, 위탁관리, 처리방침 공개 여부를 함께 확인해야 합니다.",
    agency: "개인정보보호위원회",
    sectors: ["privacy", "enterprise", "public", "education", "food", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["privacy", "outsourcing", "notice", "records"],
    keywords: ["개인정보", "처리방침", "민감정보", "회원정보", "고객정보", "위탁", "CCTV", "영상정보"],
    tasks: ["개인정보 처리 목적·보유기간 점검", "처리방침 개정 공지", "수탁사 관리 현황 확인"],
    relations: [{ target: "ecommerce-act", type: "references" }],
  },
  {
    id: "ecommerce-act",
    title: "전자상거래 등에서의 소비자보호에 관한 법률",
    type: "법률",
    article: "제13조, 제17조, 제21조",
    summary: "통신판매 정보 제공, 청약철회, 환불, 금지행위 기준",
    evidence: "온라인 판매자는 상품 정보, 환불·교환 조건, 청약철회 제한 사유를 명확히 고지해야 합니다.",
    agency: "공정거래위원회",
    sectors: ["enterprise", "privacy", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["commerce", "consumer", "notice", "amendment"],
    keywords: ["온라인", "쇼핑몰", "전자상거래", "통신판매", "환불", "교환", "청약철회", "소비자"],
    tasks: ["통신판매 고지사항 점검", "환불·교환 규정 정비", "청약철회 제한 사유 표시"],
    relations: [{ target: "privacy-act", type: "references" }],
  },
  {
    id: "food-sanitation-act",
    title: "식품위생법",
    type: "법률",
    article: "제36조, 제37조, 제41조, 제44조",
    summary: "식품접객업 영업신고, 시설기준, 위생교육, 영업자 준수사항",
    evidence: "음식점·카페 창업은 영업신고, 시설기준, 위생교육, 원산지·표시 기준을 함께 확인해야 합니다.",
    agency: "식품의약품안전처",
    sectors: ["food", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["food", "permit", "reporting", "safety", "notice"],
    keywords: ["카페", "음식점", "식품", "위생", "영업신고", "위생교육", "원산지", "배달", "주방"],
    tasks: ["영업신고 대상 여부 확인", "시설기준·위생교육 체크", "표시·원산지 고지사항 점검"],
    relations: [],
  },
  {
    id: "housing-lease-act",
    title: "주택임대차보호법",
    type: "법률",
    article: "제3조, 제6조의3, 제7조",
    summary: "대항력, 우선변제권, 계약갱신요구권, 차임 증감 기준",
    evidence: "주택 임대차는 전입신고, 확정일자, 보증금 증액, 계약갱신요구권 행사 기한을 함께 검토해야 합니다.",
    agency: "법무부",
    sectors: ["realestate", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["lease", "realestate", "contract", "notice"],
    keywords: ["임대차", "전세", "월세", "보증금", "계약갱신", "확정일자", "전입신고", "오피스텔", "주택"],
    tasks: ["계약갱신요구권 행사 기한 확인", "보증금 증액 한도 검토", "전입신고·확정일자 증빙 확인"],
    relations: [{ target: "civil-act", type: "references" }],
  },
  {
    id: "commercial-lease-act",
    title: "상가건물 임대차보호법",
    type: "법률",
    article: "제3조, 제10조, 제11조",
    summary: "상가 임대차 대항력, 계약갱신, 차임 증감 기준",
    evidence: "상가 계약은 사업자등록, 환산보증금, 계약갱신 요구, 권리금 보호 여부를 함께 확인해야 합니다.",
    agency: "법무부",
    sectors: ["realestate", "food", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["lease", "realestate", "contract"],
    keywords: ["상가", "임대차", "권리금", "환산보증금", "사업자등록", "점포", "매장"],
    tasks: ["환산보증금 적용 범위 확인", "계약갱신·권리금 보호 검토", "사업자등록과 대항력 요건 확인"],
    relations: [{ target: "civil-act", type: "references" }],
  },
  {
    id: "building-act",
    title: "건축법",
    type: "법률",
    article: "제11조, 제14조, 제19조",
    summary: "건축허가, 신고, 용도변경, 사용승인 기준",
    evidence: "건축·리모델링·용도변경은 허가·신고 대상, 건축물 용도, 사용승인, 지자체 조례를 함께 확인해야 합니다.",
    agency: "국토교통부",
    sectors: ["construction", "realestate", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["construction", "permit", "local", "safety"],
    keywords: ["건축", "리모델링", "증축", "용도변경", "건축허가", "사용승인", "인테리어", "공사"],
    tasks: ["건축허가·신고 대상 확인", "용도지역·건축물 용도 검토", "사용승인·현장점검 일정 정리"],
    relations: [],
  },
  {
    id: "tax-vat-act",
    title: "부가가치세법",
    type: "법률",
    article: "제8조, 제31조, 제32조",
    summary: "사업자등록, 세금계산서, 부가가치세 신고·납부 기준",
    evidence: "사업 개시와 매출 발생 시 사업자등록, 과세/면세 여부, 세금계산서 발급, 신고 기간을 확인해야 합니다.",
    agency: "기획재정부",
    sectors: ["tax", "enterprise", "food", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["tax", "reporting", "commerce", "records"],
    keywords: ["부가세", "부가가치세", "세금계산서", "사업자등록", "매출", "신고", "면세", "과세"],
    tasks: ["과세·면세 여부 확인", "세금계산서 발급 기준 점검", "신고·납부 일정 등록"],
    relations: [{ target: "income-tax-act", type: "references" }],
  },
  {
    id: "income-tax-act",
    title: "소득세법",
    type: "법률",
    article: "제70조, 제127조",
    summary: "종합소득세 신고, 원천징수, 사업소득 처리 기준",
    evidence: "개인사업자와 프리랜서 거래는 종합소득세 신고, 원천징수, 필요경비 증빙을 함께 검토해야 합니다.",
    agency: "기획재정부",
    sectors: ["tax", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["tax", "reporting", "records"],
    keywords: ["소득세", "종합소득세", "원천징수", "프리랜서", "사업소득", "경비", "세무"],
    tasks: ["원천징수 대상 확인", "소득 구분과 증빙자료 정리", "신고 일정 확인"],
    relations: [],
  },
  {
    id: "air-environment-act",
    title: "대기환경보전법",
    type: "법률",
    article: "제23조, 제30조",
    summary: "대기배출시설 설치허가·신고, 방지시설 운영 기준",
    evidence: "공장 증설이나 배출시설 설치 시 허가·신고 대상, 배출허용기준, 방지시설 운영기록을 확인해야 합니다.",
    agency: "환경부",
    sectors: ["environment", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["environment", "permit", "reporting", "records"],
    keywords: ["대기", "배출시설", "공장", "환경", "방지시설", "오염", "인허가", "굴뚝"],
    tasks: ["배출시설 허가·신고 대상 확인", "배출허용기준과 측정 의무 점검", "방지시설 운영기록 관리"],
    relations: [{ target: "waste-control-act", type: "references" }],
  },
  {
    id: "waste-control-act",
    title: "폐기물관리법",
    type: "법률",
    article: "제17조, 제18조",
    summary: "폐기물 배출자 의무, 보관·처리, 위탁 처리 기준",
    evidence: "사업장 폐기물은 종류별 분류, 보관 기준, 위탁계약, 처리 실적 보고가 필요합니다.",
    agency: "환경부",
    sectors: ["environment", "enterprise", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["environment", "outsourcing", "reporting", "records"],
    keywords: ["폐기물", "사업장폐기물", "처리", "위탁", "보관", "배출자", "환경"],
    tasks: ["폐기물 종류와 배출자 의무 확인", "위탁 처리 계약 점검", "보관·처리 기록 관리"],
    relations: [{ target: "air-environment-act", type: "references" }],
  },
  {
    id: "road-traffic-act",
    title: "도로교통법",
    type: "법률",
    article: "제12조, 제53조",
    summary: "어린이 보호구역, 통학버스, 운전자 준수사항",
    evidence: "통학버스 운영은 신고, 동승보호자, 안전교육, 어린이 보호구역 운행 기준을 함께 확인해야 합니다.",
    agency: "경찰청",
    sectors: ["traffic", "education", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["traffic", "safety", "reporting", "education"],
    keywords: ["도로교통", "통학버스", "어린이", "보호구역", "운전", "교통", "차량", "학원버스"],
    tasks: ["통학버스 신고·표지 확인", "운전자·동승자 안전교육 확인", "보호구역 운행 기준 점검"],
    relations: [{ target: "private-institute-act", type: "references" }],
  },
  {
    id: "private-institute-act",
    title: "학원의 설립ㆍ운영 및 과외교습에 관한 법률",
    type: "법률",
    article: "제6조, 제15조",
    summary: "학원 설립·운영 등록, 교습비, 안전관리 기준",
    evidence: "학원 운영은 등록, 교습비 게시, 강사·시설 기준, 통학차량 안전 기준을 함께 확인해야 합니다.",
    agency: "교육부",
    sectors: ["education", "traffic", "general"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["education", "permit", "safety", "notice"],
    keywords: ["학원", "교습소", "과외", "교습비", "강사", "학교", "통학차량", "학원버스"],
    tasks: ["학원 등록·변경 신고 확인", "교습비 게시 기준 점검", "안전관리·통학차량 기준 확인"],
    relations: [{ target: "road-traffic-act", type: "references" }],
  },
  {
    id: "admin-procedure-act",
    title: "행정절차법",
    type: "법률",
    article: "제21조, 제24조",
    summary: "처분 사전통지, 의견제출, 행정문서 절차 기준",
    evidence: "인허가, 처분, 제재 대응은 사전통지, 의견제출, 처분 근거, 불복 절차를 확인해야 합니다.",
    agency: "행정안전부",
    sectors: ["public", "enterprise", "general", "construction", "environment", "food"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["notice", "reporting", "amendment", "permit"],
    keywords: ["공문", "행정", "처분", "통지", "의견제출", "절차", "인허가", "제재", "과태료"],
    tasks: ["처분 근거 조문 정리", "의견제출 기한 확인", "행정 대응 문안 초안 작성"],
    relations: [],
  },
  {
    id: "civil-act",
    title: "민법",
    type: "법률",
    article: "계약, 채권, 손해배상 관련 조항",
    summary: "계약 성립, 해제·해지, 손해배상, 채권채무 일반 기준",
    evidence: "계약 관계는 특례법 적용 여부와 별개로 민법상 계약, 해제·해지, 손해배상 기준을 함께 확인해야 합니다.",
    agency: "법무부",
    sectors: ["general", "realestate", "enterprise"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["contract", "consumer", "lease"],
    keywords: ["계약", "해지", "손해배상", "채무", "채권", "민법", "위약금"],
    tasks: ["계약 조항과 해지 사유 확인", "손해배상·위약금 범위 검토", "특별법 우선 적용 여부 확인"],
    relations: [],
  },
];

export const regionLabels = {
  auto: "자동",
  seoul: "서울",
  gyeonggi: "경기",
  busan: "부산",
  nationwide: "전국",
};

export const sectorLabels = {
  auto: "자동",
  general: "전체 법령",
  workplace: "노동·인사",
  enterprise: "기업 준법",
  public: "공공·행정",
  privacy: "개인정보",
  realestate: "부동산·임대차",
  tax: "세무",
  food: "식품·위생",
  construction: "건축·인허가",
  environment: "환경",
  traffic: "교통·안전",
  education: "교육",
  healthcare: "의료",
  fire: "소방·시설안전",
};

export const topicLabels = {
  labor: "노동법",
  hours: "근로시간",
  wages: "임금",
  safety: "안전",
  privacy: "개인정보",
  commerce: "전자상거래",
  consumer: "소비자",
  food: "식품위생",
  lease: "임대차",
  realestate: "부동산",
  contract: "계약",
  construction: "건축",
  tax: "세무",
  environment: "환경",
  traffic: "교통",
  education: "교육",
  healthcare: "의료",
  fire: "소방·화재",
  permit: "인허가",
  amendment: "개정 대응",
  local: "자치법규",
  outsourcing: "도급·위탁",
  reporting: "신고·보고",
  records: "기록관리",
  notice: "절차·고지",
};
