export const sampleScenarios = [
  "서울 소재 스타트업이 포괄임금제를 폐지하고 선택근로제를 도입하려고 합니다. 연장근로, 야간수당, 최저임금 산정, 취업규칙 변경, 근로자 동의 절차를 확인하고 싶습니다.",
  "경기 지역 제조업체가 교대제 개편과 산업안전보건 점검을 준비하고 있습니다. 근로시간, 휴게시간, 위험성평가, 도급업체 안전조치까지 같이 보고 싶습니다.",
  "부산 지점이 임금체계와 급여명세서 양식을 바꾸려고 합니다. 최저임금, 통상임금, 퇴직급여 영향과 근로자 공지 절차를 정리해 주세요.",
];

export const lawData = [
  {
    id: "labor-standards-hours",
    title: "근로기준법",
    type: "법률",
    article: "제50조, 제53조, 제56조",
    summary: "근로시간, 연장근로 제한, 연장·야간·휴일근로 가산임금 기준",
    evidence: "근로시간 제도 변경은 연장근로 한도, 휴게시간, 야간·휴일수당 산정 기준을 함께 점검해야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "hours", "wages", "amendment"],
    keywords: ["근로기준법", "근로시간", "연장근로", "야간수당", "휴일근로", "선택근로", "포괄임금", "휴게시간"],
    tasks: ["연장근로 한도와 휴게시간 재계산", "야간·휴일수당 산정표 갱신", "근로시간 기록 체계 점검"],
    relations: [
      { target: "employment-rules", type: "references" },
      { target: "minimum-wage-act", type: "tension" },
    ],
  },
  {
    id: "employment-rules",
    title: "근로기준법",
    type: "법률",
    article: "제93조, 제94조",
    summary: "취업규칙 작성·신고, 근로자 의견청취 및 불이익 변경 동의 절차",
    evidence: "임금체계나 근로시간 제도 변경은 취업규칙 개정, 의견청취, 동의 절차의 증빙을 남겨야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "notice", "amendment"],
    keywords: ["취업규칙", "근로자", "동의", "의견청취", "불이익", "변경", "공지", "신고"],
    tasks: ["취업규칙 변경안 작성", "근로자 의견청취·동의 증빙 확보", "관할 노동관서 신고자료 준비"],
    relations: [{ target: "labor-standards-hours", type: "references" }],
  },
  {
    id: "minimum-wage-act",
    title: "최저임금법",
    type: "법률",
    article: "제6조",
    summary: "최저임금 이상 지급 의무와 임금 산입 범위 검토",
    evidence: "임금체계 개편 시 기본급, 고정수당, 정기상여금, 복리후생성 임금의 산입 여부를 분리해 확인해야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "wages"],
    keywords: ["최저임금", "임금", "급여", "수당", "상여금", "복리후생", "통상임금", "급여명세서"],
    tasks: ["최저임금 산입 범위 비교", "급여명세서 항목 점검", "임금 부족분 발생 여부 산정"],
    relations: [{ target: "labor-standards-hours", type: "tension" }],
  },
  {
    id: "industrial-safety-act",
    title: "산업안전보건법",
    type: "법률",
    article: "제36조, 제38조",
    summary: "위험성평가, 안전조치, 사업장 안전보건 관리 기준",
    evidence: "근무제 개편이나 도급 작업 변경 시 위험성평가와 안전보건 교육, 작업별 안전조치가 함께 갱신되어야 합니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "safety", "reporting", "outsourcing"],
    keywords: ["산업안전", "안전보건", "위험성평가", "도급", "협력업체", "제조", "작업", "안전조치"],
    tasks: ["위험성평가 실시 여부 확인", "안전보건 교육 계획 갱신", "도급·협력업체 안전조치 점검"],
    relations: [{ target: "employment-rules", type: "references" }],
  },
  {
    id: "retirement-benefit-act",
    title: "근로자퇴직급여 보장법",
    type: "법률",
    article: "제4조, 제8조",
    summary: "퇴직급여 제도 설정, 평균임금 기반 퇴직금 산정 기준",
    evidence: "임금 항목 변경은 평균임금과 퇴직급여 산정 기준에 후행 영향을 줄 수 있습니다.",
    agency: "고용노동부",
    sectors: ["workplace", "enterprise", "public"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["labor", "wages", "records"],
    keywords: ["퇴직급여", "퇴직금", "평균임금", "임금체계", "급여", "정산"],
    tasks: ["퇴직급여 산정 기준 영향 검토", "평균임금 산정 항목 재확인", "임금 변경 이력 보관"],
    relations: [{ target: "minimum-wage-act", type: "references" }],
  },
  {
    id: "admin-procedure-act",
    title: "행정절차법",
    type: "법률",
    article: "제21조, 제24조",
    summary: "처분 사전통지, 의견제출, 행정문서 절차 기준",
    evidence: "기관 대응 문서는 통지, 의견제출, 처분 근거를 절차별로 남겨야 합니다.",
    agency: "행정안전부",
    sectors: ["public", "enterprise", "workplace"],
    regions: ["nationwide", "seoul", "gyeonggi", "busan"],
    topics: ["notice", "reporting", "amendment"],
    keywords: ["공문", "행정", "처분", "통지", "의견제출", "절차"],
    tasks: ["행정 대응 문안 초안 작성", "통지·의견제출 기한 확인", "처분 근거 조문 정리"],
    relations: [],
  },
];

export const regionLabels = {
  auto: "자동",
  seoul: "서울",
  gyeonggi: "경기",
  busan: "부산",
  nationwide: "전국",
};

export const sectorLabels = {
  auto: "자동",
  workplace: "노동·인사",
  public: "공공기관·지자체",
  enterprise: "기업 준법",
};

export const topicLabels = {
  labor: "노동법",
  hours: "근로시간",
  wages: "임금",
  safety: "산업안전",
  amendment: "개정 대응",
  local: "자치법규",
  outsourcing: "도급·위탁",
  reporting: "신고·보고",
  records: "기록관리",
  notice: "행정절차",
};
